services:
  mongodb:
    image: mongo:7.0.21-rc0-jammy
    
    container_name: mongodb

    ports:
      - "27007:27017"
    volumes:
      - ./mongodb:/data/db

    networks:
      - backend

    restart: always

networks:
  backend: